import testData from '../..//support/testData';

function RegistrationFormTest() {
    cy.contains('a', 'Registration Form').click();
    const waitForLoading = () => {
        cy.task("log", "⏳ Waiting for loader to disappear");
        cy.get(".loader", { timeout: 15000 }).should("not.exist");
        cy.wait(1000); 
    }
    waitForLoading();
    cy.get('input[type="button"][value="Start"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[aria-label="First Name"]').click().type(testData?.fName);
    cy.get('input[aria-label="Last Name"]').click().type(testData?.lName);
    cy.get('input[aria-label="Date of Birth"]').click().type(testData?.dob);
    cy.get('input[value="married"]').click();
    cy.get('input[value="male"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[aria-label="Emergency Contact"]').click().type(testData?.eContact);
    cy.get('input[aria-label="Relationship"]').click().type(testData?.rel);
    cy.get('input#sq_326i').click().type(testData?.fatherFName);
    cy.get('input#sq_327i').click().type(testData?.fatherLName);
    cy.get('input#sq_330i').click().type(testData?.motherFName);
    cy.get('input#sq_331i').click().type(testData?.motherLName);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_333i').click().type(testData?.ssn);
    cy.get('input#sq_333i').click().type(testData?.eContact);
    cy.get('input#sq_338i').click().type(testData?.addStreet);
    cy.get('input#sq_340i').click().type(testData?.addCity);
    cy.get('input#sq_341i').click().type(testData?.addState);
    cy.get('input#sq_342i').click().type(testData?.addZip);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_344i').click().type(testData?.insName);
    cy.get('input#sq_345i').click().type(testData?.insId);
    cy.get('input#sq_346i').click().type(testData?.insGroup);
    cy.get('input#sq_347i').click().type(testData?.insClaim);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_356i').click().type(testData?.ins2Name);
    cy.get('input#sq_357i').click().type(testData?.ins2Id);
    cy.get('input#sq_358i').click().type(testData?.ins2Claim);
    cy.get('input#sq_359i').click().type(testData?.ins2Group);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_369i').click().type(testData?.phrName);
    cy.get('input#sq_370i').click().type(testData?.phrPhone);
    cy.get('input#sq_371i').click().type(testData?.phrFax);
    cy.get('input#sq_373i').click().type(testData?.addStreet);
    cy.get('input#sq_375i').click().type(testData?.addCity);
    cy.get('input#sq_376i').click().type(testData?.addState);
    cy.get('input#sq_377i').click().type(testData?.addZip);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_381i').click().type(testData?.spFName);
    cy.get('input#sq_382i').click().type(testData?.spLName);
    cy.get('input#sq_384i').click().type(testData?.spDOB);
    cy.get('input[value="male"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_386i').click().type(testData?.spSSN);
    cy.get('input#sq_387i').click().type(testData?.spEmploye);
    cy.get('input#sq_389i').click().type(testData?.addStreet);
    cy.get('input#sq_391i').click().type(testData?.addCity);
    cy.get('input#sq_392i').click().type(testData?.addState);
    cy.get('input#sq_393i').click().type(testData?.addZip);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_394i_0').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_396i').click().type(testData?.refFName);
    cy.get('input#sq_397i').click().type(testData?.refLName);
    cy.get('input#sq_399i').click().type(testData?.refTel);
    cy.get('input#sq_401i').click().type(testData?.addStreet);
    cy.get('input#sq_403i').click().type(testData?.addCity);
    cy.get('input#sq_404i').click().type(testData?.addState);
    cy.get('input#sq_405i').click().type(testData?.addZip);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_407i').click().type(testData?.empName);
    cy.get('input#sq_407i').click().type(testData?.empWork);
    cy.get('input#sq_410i').click().type(testData?.addStreet);
    cy.get('input#sq_411i').click().type(testData?.addCity);
    cy.get('input#sq_412i').click().type(testData?.addState);
    cy.get('input#sq_413i').click().type(testData?.addZip);
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input[type="button"][value="Next"]').click();
    cy.get('input#sq_417i').click().type(testData?.authSign1);
    cy.get('input#sq_420i').click().type(testData?.authSign2);
    cy.get('input[type="button"][value="Complete"]').click();
}

export default RegistrationFormTest;