name: Cypress Tests

on: 
  schedule:
    - cron: '30 7 * * *' # Runs at 12:00 PM IST (06:30 UTC) - Note: Scheduled workflows only run if the default branch has had a commit within the last 90 days (GitHub policy to prevent resource drain).

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      # - name: List available test files
      #   run: ls -la cypress/e2e

      - name: Run selected Cypress specs
        run: npx cypress run # --spec "cypress/e2e/loginPage.cy.js,cypress/e2e/addExistingMember.cy.js,cypress/e2e/createConversation.cy.js"
        continue-on-error: true

      # - name: Install AWS CLI and jq
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y jq
      #     aws --version

      - name: Upload JSON reports to S3
        if: always()
        run: |
          echo "Uploading Cypress JSON reports to S3..."
          for file in cypress/reports/*.json; do
            echo "Uploading $file..."
            aws s3 cp "$file" "s3://projects-test-reports/hxc/$(basename "$file")"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Download filenames.json from S3 or create new
        run: |
          aws s3 cp "s3://projects-test-reports/hxc/filenames.json" filenames.json || echo '{"projectName":"HXC","filenames":[]}' > filenames.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Update filenames.json with new report files
        run: |
          for file in cypress/reports/*.json; do
            fname=$(basename "$file")
            jq --arg fname "$fname" 'if .filenames | index($fname) then . else .filenames += [$fname] end' \
              filenames.json > tmp.json && mv tmp.json filenames.json
          done

      - name: Upload updated filenames.json to S3
        run: |
          aws s3 cp filenames.json "s3://projects-test-reports/hxc/filenames.json"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Upload reports as GitHub artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-report
          path: cypress/reports/*.json
