name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: List available test files
        run: ls -la cypress/e2e

      - name: Run selected Cypress specs directly
        run: |
          echo "Running specific specs"
          npx cypress run --spec "cypress/e2e/loginPage.cy.js,cypress/e2e/addExistingMember.cy.js,cypress/e2e/createConversation.cy.js"
        continue-on-error: true

      - name: Upload Cypress JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-report
          path: cypress/reports/*.json
